"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _PaymentStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _PaymentStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_PaymentStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    PAYMENT_STATUS_UNSPECIFIED: _PaymentStatus.ValueType  # 0
    PAYMENT_STATUS_PENDING: _PaymentStatus.ValueType  # 1
    PAYMENT_STATUS_SUCCESS: _PaymentStatus.ValueType  # 2
    PAYMENT_STATUS_FAILED: _PaymentStatus.ValueType  # 3
    PAYMENT_STATUS_REFUNDED: _PaymentStatus.ValueType  # 4

class PaymentStatus(_PaymentStatus, metaclass=_PaymentStatusEnumTypeWrapper): ...

PAYMENT_STATUS_UNSPECIFIED: PaymentStatus.ValueType  # 0
PAYMENT_STATUS_PENDING: PaymentStatus.ValueType  # 1
PAYMENT_STATUS_SUCCESS: PaymentStatus.ValueType  # 2
PAYMENT_STATUS_FAILED: PaymentStatus.ValueType  # 3
PAYMENT_STATUS_REFUNDED: PaymentStatus.ValueType  # 4
Global___PaymentStatus: _TypeAlias = PaymentStatus  # noqa: Y015

class _Currency:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _CurrencyEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Currency.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    CURRENCY_UNSPECIFIED: _Currency.ValueType  # 0
    CURRENCY_RUB: _Currency.ValueType  # 1
    CURRENCY_USD: _Currency.ValueType  # 2
    CURRENCY_EUR: _Currency.ValueType  # 3

class Currency(_Currency, metaclass=_CurrencyEnumTypeWrapper): ...

CURRENCY_UNSPECIFIED: Currency.ValueType  # 0
CURRENCY_RUB: Currency.ValueType  # 1
CURRENCY_USD: Currency.ValueType  # 2
CURRENCY_EUR: Currency.ValueType  # 3
Global___Currency: _TypeAlias = Currency  # noqa: Y015

@_typing.final
class Money(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    AMOUNT_FIELD_NUMBER: _builtins.int
    CURRENCY_FIELD_NUMBER: _builtins.int
    amount: _builtins.int
    """в копейках/центах"""
    currency: Global___Currency.ValueType
    def __init__(
        self,
        *,
        amount: _builtins.int = ...,
        currency: Global___Currency.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["amount", b"amount", "currency", b"currency"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Money: _TypeAlias = Money  # noqa: Y015

@_typing.final
class PassengerInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FIRST_NAME_FIELD_NUMBER: _builtins.int
    LAST_NAME_FIELD_NUMBER: _builtins.int
    EMAIL_FIELD_NUMBER: _builtins.int
    PHONE_FIELD_NUMBER: _builtins.int
    first_name: _builtins.str
    last_name: _builtins.str
    email: _builtins.str
    phone: _builtins.str
    def __init__(
        self,
        *,
        first_name: _builtins.str = ...,
        last_name: _builtins.str = ...,
        email: _builtins.str = ...,
        phone: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["email", b"email", "first_name", b"first_name", "last_name", b"last_name", "phone", b"phone"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PassengerInfo: _TypeAlias = PassengerInfo  # noqa: Y015

@_typing.final
class PaymentEventData(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class MetadataEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    PAYMENT_ID_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    AMOUNT_FIELD_NUMBER: _builtins.int
    PASSENGER_FIELD_NUMBER: _builtins.int
    ORDER_ID_FIELD_NUMBER: _builtins.int
    TICKET_NUMBERS_FIELD_NUMBER: _builtins.int
    METADATA_FIELD_NUMBER: _builtins.int
    payment_id: _builtins.str
    status: Global___PaymentStatus.ValueType
    order_id: _builtins.str
    @_builtins.property
    def amount(self) -> Global___Money: ...
    @_builtins.property
    def passenger(self) -> Global___PassengerInfo: ...
    @_builtins.property
    def ticket_numbers(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def metadata(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    def __init__(
        self,
        *,
        payment_id: _builtins.str = ...,
        status: Global___PaymentStatus.ValueType = ...,
        amount: Global___Money | None = ...,
        passenger: Global___PassengerInfo | None = ...,
        order_id: _builtins.str = ...,
        ticket_numbers: _abc.Iterable[_builtins.str] | None = ...,
        metadata: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["amount", b"amount", "passenger", b"passenger"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["amount", b"amount", "metadata", b"metadata", "order_id", b"order_id", "passenger", b"passenger", "payment_id", b"payment_id", "status", b"status", "ticket_numbers", b"ticket_numbers"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PaymentEventData: _TypeAlias = PaymentEventData  # noqa: Y015
